language: ruby

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - bundle exec appraisal install

services:
  - mongodb

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - jruby-19mode
  - ruby-head
  - jruby-head

sudo: false

notifications:
  email: false

matrix:
  allow_failures:
    - rvm: 2.3
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: jruby-head
